# Generated by Django 3.1.7 on 2021-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('desc', models.TextField(blank=True, default='none', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
