# Generated by Django 3.1.7 on 2021-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
